apiVersion: v1
kind: Service
metadata:
  name: aegis
  labels:
    app: aegis
spec:
  selector:
    app: aegis
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 9090
      targetPort: 9090
  type: ClusterIP
